#!/usr/bin/env bash
# setup environment

#
# CONFIG
#
GIT_REPO=https://github.com/delonnewman/dotfiles.git
TMP_DIR=$HOME/tmp
PREREQS=(git curl)

function pkg-install {
	pkgs=$@
	for pkg in ${pkgs[@]}; do
		pkg_status=$(dpkg-query -W -f='${Status} ${Version}\n' $pkg 2> /dev/null)
		if [[ $pkg_status =~ 'installed' ]]; then
			echo $pkg is already installed.
		else
			echo Installing $pkg...
			sudo apt-get -y --force-yes install $pkg
			echo DONE.
		fi
	done

}

echo "=> installing prereqs..."
pkg-install ${PREREQS[@]}
echo

if [ ! -e $TMP_DIR ]; then
	mkdir $TMP_DIR
fi

cd $TMP_DIR
git clone $GIT_REPO
