#!/usr/bin/env perl
use v5.14;
use File::Path qw{ make_path };

sub sh(@) {
	if ( system(@_) == 1 ) { 0 }
	else                   { 1 }
}

make_path("$ENV{HOME}/.vim/autoload", { verbose => 1 });
make_path("$ENV{HOME}/.vim/bundle", { verbose => 1 });

say "Installing pathogen from Github...";
sh 'git submodule update --init ext/vim/pathogen' &&
sh "cp ext/vim/pathogen/autoload/pathogen.vim $ENV{HOME}/.vim/autoload";
say 'done.';

say "Installing vundle from Github...";
sh 'git submodule update --init ext/vim/vundle' &&
sh "cp -r ext/vim/vundle $ENV{HOME}/.vim/bundle";
say 'done.';
