#!/usr/bin/env bash
# setup environment

#
# CONFIG
#
RUBY_VERSION=1.9.3
GIT_REPO=https://github.com/delonnewman/dotfiles.git
SELF_URL=https://raw.github.com/delonnewman/dotfiles/master/scripts/setup
TMP_DIR=/tmp
PREREQS=(git curl build-essential bison openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev vim)
PACKAGES=(vim-gnome tig openssh-client htop)
GEMS=(rake)

FETCH_SRC="
#!/bin/sh
bash < <(curl -s $SELF_URL)
"

#
# COLORS
#

function pkg_install {
	pkgs=$@
	for pkg in ${pkgs[@]}; do
		pkg_status=$(dpkg-query -W -f='${Status} ${Version}\n' $pkg 2> /dev/null)
		if [[ $pkg_status =~ 'installed' ]]; then
			echo $pkg is already installed.
		else
			echo Installing $pkg...
			sudo apt-get -y --force-yes install $pkg
			echo DONE.
		fi
	done

}

echo '/\ |_ () |-| /\'

echo
echo "=> installing prereqs..."
echo

# install prereqs
pkg_install ${PREREQS[@]}
echo

# install RVM
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
	echo rvm is already installed.
else
	echo "--> installing RVM..."
	bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)
	bash # reload bash env
fi

# install ruby with RVM
ruby=$(ruby -v)
if [[ $ruby =~ $RUBY_VERSION ]]; then
	echo ruby-$RUBY_VERSION is already installed.
else
	echo "---> installing Ruby $RUBY_VERSION"
	# install ruby version and set as default
	[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
	rvm install $RUBY_VERSION && rvm use $RUBY_VERSION --default
fi

echo
echo '==> installing some default gems...'
echo '@@ <Thar be treasure!> @@'
echo

for gem in ${GEMS[@]}; do
	if [[ $(gem list $gem) =~ $gem ]]; then
		echo $gem is already installed.
	else
		echo installing $gem...
		rvm $RUBY_VERSION gem install $gem
	fi
done

echo
echo 'DONE.'

echo
echo 'WOOT!'
echo "===> fetching dotfiles repo from $GIT_REPO..."
echo

# if needed clean up after previous (failed) installation
if [[ -e "$TMP_DIR/dotfiles" ]]; then
	rm -f "$TMP_DIR/dotfiles"
fi

# install dotfiles
cd $TMP_DIR &&
git clone --depth 1 -- $GIT_REPO &&
cd dotfiles &&
rake install

# clean up after yourself :-|
if [[ -e "$TMP_DIR/dotfiles" ]]; then
	rm -rf "$TMP_DIR/dotfiles"
fi

# install other packages
echo
echo OK, the basics are done.
echo '====> installing some other useful packages...'
echo

pkg_install ${PACKAGES[@]}

echo
echo "DONE."
echo

echo "====> installing myself in $HOME/bin/setup..."
echo "$FETCH_SRC" > $HOME/bin/setup
chmod +x  $HOME/bin/setup
echo 'DONE. @> <tweet!>'
echo '     <|>'
echo '      ^ '

echo
echo 'Your environment is configured as best I know how ;-)'
echo "NOTE: if you need me again just type 'setup'"
echo

