" General
set nocompatible
filetype on
filetype plugin on
filetype indent plugin on
set ofu=syntaxcomplete#Complete
set modeline
set history=1000
set clipboard+=unnamed
set ffs=unix,dos,mac
set viminfo+=!

" Pathogen
call pathogen#infect()

" Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Bundles
" General
Bundle "gmarik/vundle"
Bundle "tpope/vim-surround"
Bundle "scrooloose/nerdtree"
Bundle "mattn/zencoding-vim"
Bundle "mattn/webapi-vim"
Bundle "mattn/gist-vim"
Bundle "mattn/calendar-vim"
Bundle "taglist.vim"
Bundle "mileszs/ack.vim"
Bundle "vimwiki"

" Git
Bundle "tpope/vim-fugitive"

" Perl
Bundle "vim-perl/vim-perl"

" Ruby
Bundle "tpope/vim-rails"
Bundle "tpope/vim-haml"
Bundle "tpope/vim-bundler"
Bundle "tpope/vim-rake"
Bundle "vim-ruby/vim-ruby"

" Markdown
Bundle "tpope/vim-markdown"

" Java/JVM
Bundle "tpope/vim-classpath"

" Clojure
Bundle "kien/rainbow_parentheses.vim"
Bundle "tpope/vim-leiningen"
Bundle "tpope/vim-fireplace"
Bundle "guns/vim-clojure-static"
Bundle "guns/vim-clojure-highlight"

au FileType clojure RainBowParenthesesToggle


" Theme/Colors
set background=dark
syntax on

" Vim UI
set wildmenu
set ruler
set cmdheight=1
set number
set lz " do not redraw when running macros
set hid " change buf without saving
set backspace=2
set whichwrap+=<,>,h,l
set shortmess=atI

" Visual Cues
set mat=5 " rate of bracket blinkage (in tenths of a sec)
set nohlsearch " no hightligh for search phrases
set incsearch " but do highlight while searching
set so=10
set statusline=%F%m%r%h%w\ \|\ format:%{&ff}\ \|\ type:%y\ \|\ ascii:\%03.3b\ \|\ l%4.4l,\ c%4.4v\ \|\ %3.3p%%\ \|\ len:%L 
set laststatus=2 " always show the status line

" Text Formatting/Layout
set ai " autoindent
set si " smartindent
set cindent " c style indenting
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set wrap
set smarttab
